### ISSUE TITLE
cpackget list command prints superfluous 'blaaaaa'

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/cpackget#100]
**Describe the bug**
When running `cpackget list` the output contains the info message 'blaaaaa'

**To Reproduce**
1. run cpackget list
2. See info: 
```
C:\Open-CMSIS-Pack\ctools\bin>cpackget list
I: Using pack root: "c:\CMSIS-PACKS"
I: Listing installed packs
I: blaaaaa
I: AmbiqMicro::Apollo_DFP@1.2.0
...
``` 
**Expected behavior**
```
C:\Open-CMSIS-Pack\ctools\bin>cpackget list
I: Using pack root: "c:\CMSIS-PACKS"
I: Listing installed packs
I: AmbiqMicro::Apollo_DFP@1.2.0no 'blaaaaa' in the output of listed packs
...
```

**Environment (please complete the following information):**
 - OS: windows 10
 - Version 0.5.0

**Additional context**
utils.go line 291
func CleanPath
log.Info("blaaaaa")

**Comment by chaws** [comment]
Argh, Sorry about it. Leftover debugging message when I did this PR: https://github.com/Open-CMSIS-Pack/cpackget/pull/64
Fixed in https://github.com/Open-CMSIS-Pack/cpackget/commit/502c3d60fbc780a6de544d81130f9864af835c72

Thanks for raising the issue!
