### ISSUE TITLE
local packs file: sort pindex ?

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/cpackget#103]
Hi

Do you think it could be easy and nice to sort each pdsc line in .Local/local_repository.pidx ? :-)

Thx

**Comment by lud0v1c** [comment]
Currently the local .pidx gets new entries concatenated to the end of `<pindex>`, do you mean sorting as grouping packs from the same Vendor and listing them from newest to oldest version?

**Comment by jkrech** [comment]
Please keep in mind that for this to be useful, we need to extend the specification such that **all** tools editing the `local_repository.pidx` would follow the same sorting.
In my opinion we should not require tools to sort XML elements by `attribute values`.
I rather think that the tools could sort the output when listing the content (e.g. cpackget list packs could sort the output, or even group by public, local and local-repository packs.

**Comment by jeromecoutant** [comment]
This was a quick question to open discussion...

I agree that `cpackget.exe list` is OK
(except #100 :-))

**Comment by DavidJurajdaNXP** [comment]
I am supporting canonical order. It is useful for diff. I would prefer files ordered in standard way by common formatting tool. Same principal should be applied also for *.pdsc and csolution.yml.

**Comment by lud0v1c** [comment]
Any further discussion/comment on this? Have other tools been updated to support this behaviour? @jeromecoutant

**Comment by lud0v1c** [comment]
Closing for now.
