### ISSUE TITLE
local_repository.pidx url is specified with backward slashes by cpackget on windows

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/cpackget#104]
**Describe the bug**
local_repository.pidx url is specified with backward slashes by cpackget on windows, despite the Open-CMSIS-Pack specification requiring to only use forward slashes for compatibility across host platforms.

As a side effect, same pdsc file can be added with MDK PackInstaller and cpackget only differing in slashes:

```
<pindex>
  <pdsc vendor="ARM" url="file://localhost/C:/Projects/MDK/PACK/PACK/ARM/PreInclude/" name="PreInclude" version="0.0.1"></pdsc>
  <pdsc vendor="ARM" url="file://localhost/c:\Projects\MDK\PACK\PACK\ARM\PreInclude\" name="PreInclude" version="0.0.1"></pdsc>
```

**To Reproduce**
1. Run MDK pack installer and add a pdsc file
2. Run cpackget add <path>/<filename>.pdsc 
with the same pdsc filename
3. See error

**Expected behavior**
Only specify forward slashes and identical pdsc files must only be listed once.

**Environment (please complete the following information):**
 - OS: windows
 - Version [Windows 10]

**Additional context**

**Comment by lud0v1c** [comment]
@jkrech fixed. To conclude this issue, is the upper `<vendor>` tag also forward-slash only? e.g:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<index schemaVersion="1.1.0">
 <vendor>tmp\.Local\local_repository</vendor>
 <url></url>
 <pindex>
  <pdsc vendor="TheVendor" url="file://localhost/Z:/testdata/integration/1.2.3/" name="PackName" version="1.2.3"></pdsc>
 </pindex>
</index>
```

**Comment by jkrech** [comment]
The above use of <vendor> and <url> tags is incorrect.
Like in a pdsc file the <url> and <vendor> and <name> are used to specify the origin/location of the file.
<url><vendor>.<name>.pdsc
For the pidx files the schema has <vendor> and <url>. The location of a vendor index file is
<url><vendor>.pidx
In this case the filename is "local_repository", therefore the name tag needs to be local_repository and the <url>  the absolute location on disc. 
```
<url>file://localhost/c:/tmp/.local</url>
```
only using forward slashes here as well.
Does that make sense to you, too?

**Comment by lud0v1c** [comment]
Yes it does. Can you confirm the paths are correct on your side (apart from the backward slashes)? I used a PDSC from the local integration tests, on a new pack root/installation.

**Comment by jkrech** [comment]
Not sure I understand. I have used version 0.7.1 of cpackget on Windows right now and added a local repository.

```
<?xml version="1.0" encoding="UTF-8"?>
<index schemaVersion="1.1.0">
 <vendor>c:\tmp\packroot\.Local\local_repository</vendor>
 <url></url>
 <pindex>
  <pdsc vendor="Keil" url="file://localhost/c:\Projects\MDK\PACK\PACK\STMicroelectronics\STM32F1xx_DFP\" name="STM32F1xx_DFP" version="2.4.1-dev0"></pdsc>
 </pindex>
</index>
```
Does that help?

**Comment by lud0v1c** [comment]
Yes. I will change the `<vendor>` XML path tags to only include forward slashes too.

**Comment by jkrech** [comment]
No, the `<vendor>` needs to be constant:
`<vendor>local_repository</vendor>`
The path to the local_repository.pidx file needs to be specified using forward slashes in `<url>` tag
`<url>file://localhost/c:/tmp/packroot/</url>`
Would you agree?

**Comment by lud0v1c** [comment]
Yes, that makes sense. So it's just not a case of the PDSC files not matching the specification (using `\` instead of `/`), but the local index's XML is also not matching the `index/vendor` and `index/url` tags specification correct? If so, maybe it's best to open a separate issue regarding that.

**Comment by jkrech** [comment]
Feel free to open a new issue for that if that makes it cleaner for your PRs.
