### ISSUE TITLE
[cpackget] additional command to download latest versions of all pdsc files from index.pidx (in .Web folder)

### ISSUE THREAD

**Issue by jkrech** [Open-CMSIS-Pack/cpackget#107]
cpackget was intentionally designed to not rely on the presence/cache of all pdsc files listed in the index.pidx of the .Web folder.
In case cpackget is used in the context of a tool that requires to collect information from all latest public package description files, it would be desirable to have cpackget offering this functionality. E.g.
```
cpackget init <url> --all-pdsc-files
```

**Comment by JonatanAntoni** [comment]
Incremental update of an existing cache not to forget. Initial download of the Keil index with all its listed pdsc files takes its time already today. Fetching each file separately adds a lot of overhead in today's index layout.

**Comment by lud0v1c** [comment]
> @JonatanAntoni Please review: updating the index (https://github.com/Open-CMSIS-Pack/cpackget/blob/main/README.md#updating-the-index) By default the pdsc files present in the .Web folder will get updated if required or even removed in case the pack is no longer present in the index.pidx. So this functionality would be already covered.

Also verified this. @JonatanAntoni any behavior you would like to see implemented regarding downloading .pdsc files?
