### ISSUE TITLE
Folder permission issue

### ISSUE THREAD

**Issue by jeromecoutant** [Open-CMSIS-Pack/cpackget#118]
Hi

It seems that, after installation, cpackget set 0400 permission for all folders in $CMSIS_PACK_ROOT

It is then not easy to delete/update them after...

Thx

**Comment by jeromecoutant** [comment]
Issue occurs since #56

**Comment by lud0v1c** [comment]
Hey Jerome, this is an intended feature implemented since cpackget v0.7.0. Issue #56 is resolved in #109.
The pack root in theory should not be edited manually but by the dedicated tools, what is it that you are trying to achieve?

**Comment by jeromecoutant** [comment]
I got a script that removes current pack directory before re-install a new one

**Comment by jkrech** [comment]
@jeromecoutant we have no plans to revert the "protection" of the CMSIS_PACK_ROOT folder. Could you please update you script to change the permissions prior to deleting a pack directory? Please close the issue if this is acceptable or propose an approach to deal with your use case.

**Comment by jeromecoutant** [comment]
OK for me
