### ISSUE TITLE
Install local packs using wildcards and from a folder

### ISSUE THREAD

**Issue by spcaipers-arm** [Open-CMSIS-Pack/cpackget#123]
**Describe The Problem To Be Solved**
It would be useful to install multiple packs (especially when you do not know the pack names e.g. running in CI) and also install all packs found in a folder (also recursively).

**(Optional): Suggest A Solution**
Install local packs using wildcards and from a folder (with an option for recursivity)
CLI example:
`cpackget add *.pack`
`cpackget add -r folder/` -- optional r for recursivity.

**Comment by jkrech** [comment]
@spcaipers-arm 
Are you aware that you could simply create a file containing a list of pack files to be installed using
`cpackget add -f packlist.txt` ?
Also you can now run `csolution -s my.csolution.yml list packs -m > packlist.txt` to create the list of packs used by a solution.
