### ISSUE TITLE
[cpackget] Debug log level not working on some commands

### ISSUE THREAD

**Issue by lud0v1c** [Open-CMSIS-Pack/cpackget#131]
**Describe the bug**
The `-v` flag is not showing debug verbose messages in some commands, like the recently added `checksum-` and `signature-` commands.

**To Reproduce**
`cpackget signature-create -v Pack.Vendor.1.2.3.pack -k key.pem -c cert.pem` or any valid input for the command to run.

**Expected behavior**
Debug messages should be printed.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.1 LTS
 - Version v0.8.3

**Comment by thorstendb-ARM** [comment]
Init was missing:
`PersistentPreRunE: configureInstaller`

**Comment by jkrech** [comment]
I am not sure how to validate this:

`cpackget checksum-create ARM.CMSIS.5.9.0.pack -v`
does not print anything but maybe this is expected.
