### ISSUE TITLE
On Windows message `Extracting files` is printed to multiple lines

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/cpackget#141]
**Describe the bug**
With Windows `cmd` the message `Extracting files` is printed multiple times. 

**To Reproduce**
1. Run `cpackget add -f <file>` to install missing packs
2. See error in the image below
![image](https://user-images.githubusercontent.com/8268058/205936666-d7dda565-571f-4c6d-965b-9f6ccf598475.png)

**Expected behavior**
It would be expected to see the same behavior as with the line `Downloading...`to happen.

**Environment (please complete the following information):**
 - OS: Windows 10
 - cpackget version 0.8.5

**Comment by jkrech** [comment]
@ReinhardKeil could you please try to resize your window to allow longer lines to display without line breaks?
@lud0v1c could we change the design and keep the whole line for the progress bar. We need to stay within the default width of a command shell and the available characters:

`I: Extracting files to C:\Users\jkrech\AppData\Local\Arm\Packs\ARM\CMSIS\5.9.0 100% |███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (8642/8642, 196 it/s)
`
e.g. 
`100% ███████████████████████████████████████████████| (8642/8642, 196 it/s)`

**Comment by lud0v1c** [comment]
I'll have to look at the terminal module that we're using - but I'm guessing that is possible yes.

**Comment by lud0v1c** [comment]
The main problem is fixed now. Regarding what you said @jkrech, are you suggesting we drop printing the log message about what's being extracted and just keep the bar? That would in fact make it more stable, as it is the log message that "breaks" the progress bar.

**Comment by jkrech** [comment]
I was thinking about two lines the first one where you extract to and the other is the progress bar .
```
 I: Extracting files to C:\Users\jkrech\AppData\Local\Arm\Packs\ARM\CMSIS\5.9.0
 45% |                             | (3953/8642, 98 it/s) [37s:47s]
```

**Comment by lud0v1c** [comment]
Set the bar below the message as suggested and also synced the behavior between the "Downloading" and "Extracting" actions.
