### ISSUE TITLE
Enhancement Request : could we get a list command

### ISSUE THREAD

**Issue by LMESTM** [Open-CMSIS-Pack/cpackget#2]
**Enhancement request**
Could we get a 
cpackget pack list [-cache]
command that provides the list of currently available in the pack root folder and optionally in .download cache folder

**Comment by chaws** [comment]
Just pushed a PR allowing cpackget to:
* List only installed packs: `cpackget pack list`
* List cached packs: `cpackget pack list --cached`
* List packs available in the public index: `cpackget pack list --public`

More examples are in the PR.
