### ISSUE TITLE
[cpackget] fails to install packs with "permission denied" error

### ISSUE THREAD

**Issue by JonatanAntoni** [Open-CMSIS-Pack/cpackget#213]
**Describe the bug**

Under certain circumstances cpackget fails to install a pack, e.g.,

```
/ $ cpackget add ARM::CMSIS
I: Using pack root: "/home/runner/.cache/arm/packs" (default mode - no specific CMSIS_PACK_ROOT chosen)
I: Adding pack "ARM::CMSIS"
E: mkdir KSLBEmaCod/: permission denied
E: fail to create directory
```

**To Reproduce**

1. Open a shell on Linux (or Mac)
2. Set the current working directory (cwd) to root (or any other location the current user does *not* have write permissions in).
3. Try to install a new pack, e.g., ARM::CMSIS.
4. Watch cpackget trying to create a temp directory in the cwd which fails with `permission denied`.

**Expected behavior**

It is expected that `cpackget` performs its actions independently from the cwd. Moreover, it is expected that cpackget does *not* touch files outside a dedicated system/user temp folder *or* the `CMSIS_PACK_ROOT`.

**Environment (please complete the following information):**
 - OS: Linux
 - Version Ubuntu 20.04

**Additional context**
Probably all OSes and versions are affected where the current user might not have privileges to create new subfolders in certain places used as working directory.

The immediate issue comes from here: https://github.com/Open-CMSIS-Pack/cpackget/blob/2e11b3d87432c2688df9cae89aa0aed9ea3c5682/cmd/installer/pack.go#L167-L171

Instead of "manually" creating a random temp folder at the cwd it might be better to use library functions to receive an "official" temp directory (in a system/user temp folder).

**Comment by thorstendb-ARM** [comment]
fixed by using os.TempDir(). Was same code without os.TempDir, which caused the temp operation to be executed in CWD.
```
tmpPdscFileName := filepath.Join(os.TempDir(), utils.RandStringBytes(10))
defer os.RemoveAll(tmpPdscFileName)
```
