### ISSUE TITLE
Add option `--deprecated` to omit deprecated packs by default

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/cpackget#247]
**Describe The Problem To Be Solved**
There are many deprecated packs that should be not processed by default as it may give the wrong impression.
Today the `cpackget list --public` lists all public packs regardless of the `deprecated` status.

**Suggest A Solution**
Add a command line option `--deprecated` or `-d` to include also deprecated packs.  The list should then indicate the deprecated status and propose a replacement pack if available.

**Comment by jkrech** [comment]
Merged with #246.
