### ISSUE TITLE
[cpackget] must strip meta data  from version 

### ISSUE THREAD

**Issue by edriouk** [Open-CMSIS-Pack/cpackget#268]
**Describe the bug**
Currently cpackget does not remove meta data information from versions before comparison and processing.
According to Semantic Versioning, meta-data located after '+' character should be ignored.

**To Reproduce**
1. Run the cpackget with the following args
`cpackget add ARM::CMSIS@6.0.0`
That installs ARM::CMSIS@6.0.0 pack or says it is already installed
2. Repeat command with the following command line: 
`cpackget add ARM::CMSIS@6.0.0+meta`
This command fails with the following output:
```
I: Adding pack "ARM::CMSIS@6.0.0+meta"
E: pack version not found in the pdsc file
```

**Expected behavior**
Executing `cpackget add ARM::CMSIS@6.0.0+meta` command should succeed and install ARM::CMSIS@6.0.0 pack or report it is already installed.

see also related problem #224

**Comment by edriouk** [comment]
Fixed in PR #273

**Comment by jkrech** [comment]
Validation fails.

**Comment by jkrech** [comment]
Validated the build successfully: https://github.com/Open-CMSIS-Pack/cpackget/actions/runs/8355669787

1.0.0-dev0 installs into directory: `1.0.0-dev0` 
1.0.0+meta0 installs into directory: `1.0.0`
