### ISSUE TITLE
Auto-update public index file when used but only once per day and when connection available

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/cpackget#355]
**The Problem To Be Solved**

When new packs are released, the user need to execute `cpackget update-index` before these packs become available.

**(Optional): Suggest A Solution**

The cpackget tool should automatically executed `cpackget update-index --sparse` to get the list of latest packs.  It should be sufficient to execute this once per day.  There might be an option `--no-auto-update` to disable that, even when I personally struggle to see a need for that.

**Comment by jkrech** [comment]
Validate nightly build of CMSIS-Toolbox 2024-12-09:
Tempering with the <timestamp> in index.pidx triggers a download of index.pidx when the date is smaller than today's date.
