### ISSUE TITLE
[Bug]: cpackget does not remove pdsc files in the .Web folder which ones are not listed anymore in the .Web/index.pidx file.

### ISSUE THREAD

**Issue by Evagan2018** [Open-CMSIS-Pack/cpackget#387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Scenario:
After the last update of the **.Web** folder it could happend that a vendor take back one or more of its published packs. 
In that case the affected packs are not available anymore for download and therefore they are not listed in the **index.pidx** file.
Executing  **cpackget init https://www.keil.com/pack/index.pidx -a** should  remove these pdsc files from the **.Web** folder.

### Expected Behavior

Initial state: 
The packs referenced by  **Vendor01.NameEx01_DFP.pdsc** and **Vendor01.NameEx01_DFP.pdsc** are available for download.
After an update the content of the **PACK/.Web/** folder should look like:

    ~   ~   ~   ~   ~
    │   │   │   │   └── PACK/
    │   │   │   │       │ 
    │   │   │   │       ├── .Download/
    │   │   │   │       ├── .Local/
    │   │   │   │       │   └── local_repository.pidx
    │   │   │   │       ├── .Web/
    │   │   │   │       │   ├── index.pidx
    │   │   │   │       │   ├── <xxxx>.pdsc
    │   │   │   │       │   ├── :::::::::::
    │   │   │   │       │   ├── Vendor01.NameEx01_DFP.pdsc
    │   │   │   │       │   ├── Vendor01.NameEx02_DFP.pdsc
    │   │   │   │       │   ├── :::::::::::
    │   │   │   │       │   └── <zzzz>.pdsc
    │   │   │   │       └── pack.idx
    │   │   │   │
    ~   ~   ~   ~

After some time the mentioned packs are not anymore available for download. The vendor take them back.
After an update the content of the **PACK/.Web/** folder should look like:

    ~   ~   ~   ~   ~
    │   │   │   │   └── PACK/
    │   │   │   │       │ 
    │   │   │   │       ├── .Download/
    │   │   │   │       ├── .Local/
    │   │   │   │       │   └── local_repository.pidx
    │   │   │   │       ├── .Web/
    │   │   │   │       │   ├── index.pidx
    │   │   │   │       │   ├── <xxxx>.pdsc
    │   │   │   │       │   ├── :::::::::::
    │   │   │   │       │   └── <zzzz>.pdsc
    │   │   │   │       └── pack.idx
    │   │   │   │
    ~   ~   ~   ~

### Steps To Reproduce

1. Run **cpackget init https://www.keil.com/pack/index.pidx -a -R ./PACK**
2. Goto the folder **./PACK/.Web/**
3. Mark some *.pdsc files, copy them, and paste them into the **./PACK/.Web/** folder. These additional pdsc files should appear as **Vendor01.NameEx01_DFP - Copy.pdsc** and **Vendor01.NameEx01_DFP - Copy.pdsc**. These pdsc files are not listed in the **index.pidx** file.
4. Run again **cpackget init https://www.keil.com/pack/index.pidx -a -R ./PACK**
   You will see after this update, that these pdsc files are still there.

### Affected tools

- [ ] cbuild
- [ ] cbuild2cmake
- [X] cpackget
- [ ] csolution
- [ ] packchk
- [ ] svdconv

### Affected operating systems

- [X] Windows amd64
- [ ] Windows arm64
- [ ] Linux amd64
- [ ] Linux arm64
- [ ] MacOS amd64
- [ ] MacOS arm64

**Comment by jkrech** [comment]
I think `cpackget init` command is assuming that the `.Web` is empty. Probably it should check that explicitly and consider removing all pdsc files first.

`cpackget update-index -a` should be the command to align pdsc files listed in `index.pidx` with the files contained in `.Web`.

**Comment by Evagan2018** [comment]
I can confirm that the command **cpackget update-index -a** should be used to align pdsc files 
listed in **index.pidx** with the files contained in **.Web** folder


The following test with outdated ***.pdsc** files in the **.\PACK\.Web** folder has been executed

**Steps** 

**1.**  Copy and rename the following pdsc files (only the PackName has been modified).
  - .\PACK\.Web\3PEAK.TPS325M5_DFP.pdsc    --->  3PEAK.CopyTPS325M5_DFP.pdsc
  - .\PACK\.Web\3PEAK.TPS325M0_DFP.pdsc    --->  3PEAK.CopyTPS325M0_DFP.pdsc

**2.** Change the PackName of these pdsc files (remove first the read-only flag).
   - .\PACK\.Web\3PEAK.CopyTPS325M5_DFP.pdsc    Change the PackName entry to CopyTPS325M5_DFP.
   - .\PACK\.Web\3PEAK.CopyTPS325M0_DFP.pdsc    Change the PackName entry to CopyTPS325M0_DFP.

**3.**  Modify the index.pidx file (remove the read-only flag). Add entries for both renamed pdsc names to the index.pidx file.
   - pdsc url="https://mcupack.3peakic.com.cn:8286/" vendor="3PEAK" name="CopyTPS325M0_DFP" version="1.0.0" /
   - pdsc url="https://mcupack.3peakic.com.cn:8286/" vendor="3PEAK" name="CopyTPS325M5_DFP" version="1.0.0" /

**4.**  Execute the following commandline:
`cpackget update-index -a -R C:\working\UV_Setup\ARM\ARM\PACK`

`I: Updating public index`
`I: Downloading index.pidx...`
`I: 100% |████████████ :::::: ██████████████████████████████| (209/209 kB, 316 kB/s)`
`I: Updating PDSC files of installed packs referenced in index.pidx`
`W: The pack 3PEAK::CopyTPS325M0_DFP is no longer present in the updated index.pidx, deleting PDSC file "C:\working\UV_Setup\ARM\ARM\PACK\.Web\3PEAK.CopyTPS325M0_DFP.pdsc"`
`W: The pack 3PEAK::CopyTPS325M5_DFP is no longer present in the updated index.pidx, deleting PDSC file "C:\working\UV_Setup\ARM\ARM\PACK\.Web\3PEAK.CopyTPS325M5_DFP.pdsc"`
`I: Keil::Kinetis_SDK_DFP can be upgraded from "2.3.0" to "2.3.1"`
`I: Downloading Keil.Kinetis_SDK_DFP.pdsc...`
`I: 100% |████████████ :::::: ██████████████████████████████| (153/153 kB, 308 kB/s)`
`I: Downloading all PDSC files available on the public index`

**Results**
  - The mentioned pdsc files have been removed from the **.Web** folder.
  - The mentioned entries have been removed from **index.pidx** file.
