### ISSUE TITLE
Cannot install packs that contains folders

### ISSUE THREAD

**Issue by slhultgren** [Open-CMSIS-Pack/cpackget#4]
Hi, I tested installing a pack using cpackget 0.1.1, but it seems to fail if the pack contains folders.

Steps to reproduce:
1. export CMSIS_PACK_ROOT=c:/test_cmsis
2. ./cpackget.exe -vv pack add https://keilpack.azureedge.net/pack/ARM.CMSIS.5.8.0.pack

```
...
time="2021-09-03T10:26:25+02:00" level=debug msg="Inflating \"CMSIS/\""
time="2021-09-03T10:26:25+02:00" level=debug msg="Ensuring \"c:\\test_cmsis\\ARM\\CMSIS\\5.8.0\\CMSIS\\\" directory exists"
time="2021-09-03T10:26:25+02:00" level=error msg="open c:\\test_cmsis\\ARM\\CMSIS\\5.8.0\\CMSIS: is a directory"
Error: failed to create a local file
```

Tested using Git-bash on windows.

**Comment by chaws** [comment]
Hi @slhultgren , thanks for the feedback. The issue has been fixed and I rolled out a new release with the fix.

Please let me know if the bug persists.
