### ISSUE TITLE
Make index.pidx mandatory in init command

### ISSUE THREAD

**Issue by chaws** [Open-CMSIS-Pack/cpackget#53]
Issue extracted from https://github.com/Open-CMSIS-Pack/cpackget/pull/50#issuecomment-1092498508

> a) let's make index-url mandatory - where index-url may point to a local index.pidx file being e.g. generated using vidx2pidx or a a schema compliant file without entries

**Comment by jkrech** [comment]
@chaws I believe this is a valid use case, even though we are not supporting it today in MDK and ArmDS as they use the fixed download location. However I think that people could use the vidx2pidx utility to create their own set of "public" packs or even extend a public index with a company internal pack index.
