### ISSUE TITLE
Question : is it expected to download a pdsc when removing a .pack from CMSIS_PACK_ROOT ?

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/cpackget#82]
```
> cpackget.exe pack rm STMicroelectronics.Example_HAL_GPIO_Toggle
I: Using pack root: "C:\CMSIS_PACKS"
I: Removing [STMicroelectronics.Example_HAL_GPIO_Toggle]
I: Downloading STMicroelectronics.Example_HAL_GPIO_Toggle.pdsc...
```

==> is the last step really needed ?

**Comment by jkrech** [comment]
Good point. Thinking about it, I cannot see a reason to require the pdsc file download in case of removing a pack/pack version. I guess it is a side effect of how the tool is designed when "identifying" packs being one of the initial steps.
I would recommend to review the approach. The "remove" command should not care about whether this is a valid public version that is going to be removed or got somehow else installed ...
