### ISSUE TITLE
cpackget pdsc add <pdsc> urls are added incorrectly

### ISSUE THREAD

**Issue by slhultgren** [Open-CMSIS-Pack/cpackget#9]
There is an incompatibility issue with cbuild when using local pdsc files added through the "cpackget pdsc add some.pdsc"

1. The $CMSIS_PACK_ROOT/.Local/local_repository.pidx file does not contain:
```
<?xml version="1.0"?>
```
on the first line, making cbuild failing to parse the file.

2. The urls in <pdsc url="..." /> are badly formatted as "file://C:/some/path", when it needs to be "file://localhost/C:/some/path" for cbuild to find it.
https://github.com/Open-CMSIS-Pack/devtools/blob/9859231934deabea689219335fd6ba518e156e27/tools/buildmgr/cbuild/src/CbuildProject.cpp#L276

https://en.wikipedia.org/wiki/File_URI_scheme

**Comment by chaws** [comment]
Hi @slhultgren , thanks for the feedback!

I already addressed your 2 issues and made a new release here: https://github.com/Open-CMSIS-Pack/cpackget/releases/tag/v0.1.3

Let me know if the error still persists.
