### ISSUE TITLE
E: expected element type <index> but have <html>

### ISSUE THREAD

**Issue by jankap** [Open-CMSIS-Pack/cpackget#90]
**Describe the bug**
New pack location init does not work.

**To Reproduce**

``` powershell
C:\Users\<user>> cpackget init -R .\PACK_TEST\ https://keil.com/pack/index.pidx -v
I: Using pack root: "PACK_TEST"
D: Initializing PidxXML object for "PACK_TEST\.Local\local_repository.pidx"
D: Initializing PidxXML object for "PACK_TEST\.Web\index.pidx"
D: Making sure "PACK_TEST" exists
D: Making sure "PACK_TEST\.Download" exists
D: Making sure "PACK_TEST\.Local" exists
D: Making sure "PACK_TEST\.Web" exists
D: Reading pidx from file "PACK_TEST\.Web\index.pidx"
D: Updating public index with "https://keil.com/pack/index.pidx"
I: Overwriting public index file PACK_TEST\.Web\index.pidx
D: Downloading https://keil.com/pack/index.pidx to PACK_TEST\.Download\index.pidx
D: Downloaded 35731 bytes
D: Initializing PidxXML object for "PACK_TEST\.Download\index.pidx"
D: Reading pidx from file "PACK_TEST\.Download\index.pidx"
E: expected element type <index> but have <html>
```

The file does exist, but probably not in the correct directory?

![image](https://user-images.githubusercontent.com/12893844/170270689-337ee7fe-a9d1-4924-84ea-931102c190d9.png)

![image](https://user-images.githubusercontent.com/12893844/170270842-b862889a-ee9a-487c-a691-39446d06afb1.png)

**Comment by jkrech** [comment]
Correct the index.pidx needs to be located in the .Web folder:
`Downloading https://keil.com/pack/index.pidx to PACK_TEST\.Download\index.pidx`
However I think there is a problem with the command line as well.
The index.pidx file download link the 'www' is missing:
`cpackget init -R .\PACK_TEST\ https://www.keil.com/pack/index.pidx -v`

**Comment by jankap** [comment]
Oh dear, it was the `www`.

Could you please update the docs here to avoid that issue? https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/cpackget/docs/cpackget.md#specify-the-working-pack-root-folder

Thank you very much for your help!
