### ISSUE TITLE
Git-bash does not show license window on Windows

### ISSUE THREAD

**Issue by chaws** [Open-CMSIS-Pack/cpackget#95]
On Linux, there is a nice window displaying the EULA text. While on Windows that's is not the case.

**Comment by chaws** [comment]
Sorry I can't quite remember what the issue was. But if I recall it, it was an issue trying to get user agreement on the same terminal window. I think this worked well on Linux, but it was a mystery on Windows. @lud0v1c perhaps remember some of that too.

**Comment by jkrech** [comment]
Using cpackget 0.9.4 the initial problem can no longer be reproduced.
