### ISSUE TITLE
Version Number check too strict

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/cpackget#98]
Some projects use a version schema that includes `mm.yy` format. A leading `0` in the month field is not accepted by `cpackget` due to the strict checking of the semantic versioning format.

See also https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/issues/126

This results in the effect that some packs cannot be installed right now.  Example:
```PS C:\Test\Demo_EW> cpackget add ARM.ethos-u-core-driver.1.22.02     
I: Using pack root: "C:\Users\reikei01\AppData\Local\Arm\Packs"
E: bad pack name: it should be one of the following formats: Vendor.Pack, Vendor.Pack.x.y.z, Vendor.Pack.x.y.z.pack, or Vendor.Pack.pdsc
E: bad pack name: it should be one of the following formats: Vendor.Pack, Vendor.Pack.x.y.z, Vendor.Pack.x.y.z.pack, or Vendor.Pack.pdsc
```
>NOTE: It appears that errors are printed twice, which seems to be another flaw.

For the time being, I suggest to relax the check for the sematic version by using the definition ` PackVersionType` from `PACK.xsd`.

```
<xs:simpleType name="PackVersionType">
    <xs:restriction base="xs:string">
      <!-- major . minor . patch [[-]quality] [+build] -->
      <xs:pattern value="[0-9]+.[0-9]+.[0-9]+((\-[0-9A-Za-z_\-\.]+)|([_A-Za-z][0-9A-Za-z_\-\.]*)|())((\+[\-\._A-Za-z0-9]+)|())" />
    </xs:restriction>
  </xs:simpleType>
```

See also https://github.com/Open-CMSIS-Pack/Open-CMSIS-Pack-Spec/blob/main/schema/PACK.xsd#L1498

**Environment:**
`cpackget version 0.5.0 (C) 2022 Linaro`
Running on Windows 10.

**Comment by chaws** [comment]
I have extended the regex cpackget uses to allow leading zeros in the version. It is worth to mention that pack directories will have leading zeros as well.
